Repository ets-ninja/honeyMoney_backend, pull requests merged in 2022-10, with the labels that each got.

#17 Added google sign-in, logout, refresh
  .env.example
  constants/index.js
  controllers/auth.controllers.js
  controllers/user.controllers.js
  index.js
  middlewares/passport.middleware.js
  models/user.model.js
  package-lock.json
  package.json
  routes/auth.routes.js
  services/stripe/create-customer.service.js
  utils/authenticate.helpers.js
Labels: ready to merge

#19 Anton/fix bug in update user photo
  index.js
Labels: ready to merge

#23 Stripe
  .gitignore
  controllers/payment.controllers.js
  controllers/user.controllers.js
  models/basket.model.js
  models/transaction.model.js
  models/user.model.js
  routes/payment.routes.js
  services/stripe/get-connected-account.services.js
  services/stripe/transactions/custom/create-transaction.service.js
  services/stripe/transactions/stripe/change-balance.service.js
  services/stripe/transactions/stripe/create-transfer.service.js
  services/stripe/transactions/stripe/instant-payout.service.js
Labels: ready to merge

#22 Nikita/notifications init
  .DS_Store
  .env.example
  .gitignore
  controllers/auth.controllers.js
  controllers/user.controllers.js
  docs/swagger.json
  index.js
  middlewares/passport.middleware.js
  models/user.model.js
  package-lock.json
  package.json
  routes/auth.routes.js
  routes/user.routes.js
  services/notifications/index.js
Labels: ready to merge

#20 Yuliia/wishlist sorting
  controllers/wishlist.controllers.js
  routes/wishlist.routes.js
Labels: ready to merge

#27 Bogd1y/creation banka
  controllers/basket.controllers.js
  models/basket.model.js
  routes/basket.routes.js
Labels: ready to merge, waiting for review

#29 Stripe
  controllers/payment.controllers.js
  models/transaction.model.js
  routes/basket.routes.js
  routes/payment.routes.js
  services/stripe/get-connected-account.services.js
  services/stripe/transactions/custom/create-transaction.service.js
  services/stripe/transactions/stripe/create-refund.service.js
Labels: ready to merge

#28 Yuliia/wishlist create update
  controllers/wishlist.controllers.js
  models/wishlistItem.model.js
  routes/wishlist.routes.js
Labels: ready to merge

#31 Nikita/notifications to routes
  controllers/basket.controllers.js
  controllers/payment.controllers.js
  controllers/user.controllers.js
  index.js
  middlewares/passport.middleware.js
  models/participant.model.js
  routes/basket.routes.js
  routes/user.routes.js
  services/notifications/index.js
  services/stripe/transactions/custom/create-transaction.service.js
  services/stripe/transactions/stripe/create-refund.service.js
Labels: ready to merge

#34 Nikita/notifications v2
  controllers/payment.controllers.js
  index.js
  package-lock.json
  package.json
  services/notifications/index.js
Labels: ready to merge

#35 Myroslav/public page
  controllers/public.controllers.js
  index.js
  routes/public.routes.js
  services/logger/devLogger.js
  services/logger/index.js
Labels: ready to merge

#36 Stripe
  README.md
  controllers/payment.controllers.js
  models/transaction.model.js
Labels: ready to merge

#37 Updated jar controllers and routes
  controllers/basket.controllers.js
  controllers/jar.controllers.js
  controllers/payment.controllers.js
  controllers/public.controllers.js
  index.js
  models/jar.model.js
  routes/basket.routes.js
  routes/jar.routes.js
Labels: ready to merge

#39 Updates logger Readme
  README.md
Labels: ready to merge

#40 Deploy config (Revealed firebase config, changed start scripts, added missing dependency)
  .gitignore
  honeymoneyworker-firebase-adminsdk-4ru0p-4db0149331.json
  package-lock.json
  package.json
Labels: ready to merge

#46 Anton/share-bank
  controllers/jar.controllers.js
  controllers/payment.controllers.js
  index.js
  models/shareBankTransaction.model.js
  package.json
  public/favicon.svg
  public/img/Group 15.svg
  public/img/image 4.svg
  public/img/rich-pig-mascot-character-design-vector.svg
  public/index.css
  public/index.js
  routes/payment.routes.js
  routes/share-basket.routes.js
  views/error.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/partials/paymentForm.handlebars
  views/paymentIntent.handlebars
  views/success.handlebars
Labels: waiting for review

#50 Anton/fix share bank
  controllers/payment.controllers.js
  public/index.js
Labels: waiting for review

#52 Hot fixes to jar controllers
  controllers/jar.controllers.js
  controllers/public.controllers.js
Labels: ready to merge
